# Generated by Django 4.0.3 on 2023-11-19 03:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_alter_popconsanddrinks_create_at_and_more'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('genre', models.CharField(max_length=200)),
                ('trailer', embed_video.fields.EmbedVideoField()),
                ('durationInMinutes', models.PositiveSmallIntegerField()),
                ('release_date', models.DateField()),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Italian', 'Italian'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian'), ('Turkish', 'Turkish'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('posterImage', models.FileField(default='', upload_to='posters/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('isAvailable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(to='api.actor')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.director')),
            ],
        ),
        migrations.CreateModel(
            name='Showtimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('available', models.BooleanField(default=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('roomNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.room')),
            ],
        ),
        migrations.CreateModel(
            name='Evulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(help_text='Rate from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookedAt', models.DateTimeField(auto_now_add=True)),
                ('expiresIn', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'pending'), ('A', 'approved')], max_length=1)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.showtimes')),
                ('snacks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theater.popconsanddrinks')),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theater.voucher')),
            ],
        ),
    ]
