# Generated by Django 4.2.7 on 2023-11-23 15:36

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_actor_director_movie_showtimes_evulation_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtimes',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='showtimes',
            name='startTime',
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='', upload_to='actors/'),
        ),
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(default='', upload_to='directors/'),
        ),
        migrations.AddField(
            model_name='showtimes',
            name='time',
            field=django_jsonform.models.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='movie',
            name='posterImage',
            field=models.ImageField(default='', upload_to='posters/'),
        ),
    ]
