# Generated by Django 4.2.7 on 2023-11-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimes',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie'),
        ),
    ]
