# Generated by Django 4.2.7 on 2023-11-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_alter_seat_options'),
        ('api', '0005_alter_showtimes_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='api.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='directors', to='api.director'),
        ),
        migrations.AlterField(
            model_name='showtimes',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='api.movie'),
        ),
        migrations.AlterField(
            model_name='showtimes',
            name='roomNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='theater.room'),
        ),
    ]
