# Generated by Django 4.2.7 on 2023-11-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_alter_seat_options'),
        ('api', '0006_alter_movie_actors_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='directors', to='api.director'),
        ),
        migrations.AlterField(
            model_name='showtimes',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='api.movie'),
        ),
        migrations.AlterField(
            model_name='showtimes',
            name='roomNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='theater.room'),
        ),
    ]
