# Generated by Django 4.2.7 on 2023-12-06 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_alter_seat_options'),
        ('api', '0008_alter_movie_actors_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Number only', regex='^[0-9]+$')]),
        ),
        migrations.AddField(
            model_name='booking',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiresIn',
            field=models.IntegerField(default='210'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ManyToManyField(to='theater.seat'),
        ),
    ]
