# Generated by Django 4.2.7 on 2023-12-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_booking_email_booking_fullname_booking_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
