# Generated by Django 4.2.7 on 2023-12-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_actor_image_alter_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='director',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='director',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='director',
            name='nationality',
        ),
        migrations.AddField(
            model_name='actor',
            name='character',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
