# Generated by Django 4.2.7 on 2023-12-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_actor_bio_remove_actor_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
