# Generated by Django 4.2.7 on 2023-12-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_movie_director'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Director',
        ),
    ]
