# Generated by Django 4.2.7 on 2023-12-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_director'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimeUser',
        ),
    ]
