# Generated by Django 4.2.7 on 2023-11-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popconsanddrinks',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
