# Generated by Django 4.0.3 on 2023-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_alter_popconsanddrinks_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
