# Generated by Django 4.0.3 on 2023-11-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_alter_seat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seatNo',
            field=models.CharField(max_length=10),
        ),
    ]
