# Generated by Django 4.2.7 on 2023-11-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_alter_seat_seatno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['room__roomNumber', 'seatNo']},
        ),
    ]
